export const emojiList: Record<string, string> = {
  love: "❤️",
  pizza: "🍕",
  cats: "🐱",
  dog: "🐶",
  happy: "😊",
  sad: "😢",
  great: "🥰",
  sun: "☀️",
  moon: "🌙",
  star: "⭐",
  coffee: "☕",
  cake: "🍰",
  book: "📖",
  car: "🚗",
  travel: "✈️",
  music: "🎵",
  party: "🎉",
  heart: "💖",
  cool: "😎",
  hello: "👋",
  goodbye: "👋",
  rain: "🌧️",
  fire: "🔥",
  water: "💧",
};
